package Vista;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import javax.swing.AbstractButton;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.plaf.basic.BasicButtonUI;

public class jfrPantallaLogin extends javax.swing.JFrame {
    
    public jfrPantallaLogin() {
        initComponents();
        
        int width = btnVerContrasena.getWidth();
        int height = btnVerContrasena.getHeight();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagenes/no_ver_password.png"));
        Image scaledImage = icon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        btnVerContrasena.setIcon(new ImageIcon(scaledImage));
        
        new Controlador.ctrlPantallaLogin(this);
        
        
        RoundedPanel roundedPanel = new RoundedPanel();
        roundedPanel.setBackground(jpFondoAzul.getBackground());
        roundedPanel.setBounds(jpFondoAzul.getBounds());
        
        BienvenidoLabel.setBounds(60, 50, 300, 50);
        roundedPanel.add(BienvenidoLabel);
        
        btnIniciarSesion.setBounds(35, 320, 350, 40);
        roundedPanel.add(btnIniciarSesion);
        
        btnIniciarSesion.setUI(new jfrPantallaLogin.RoundedButtonUI());
        
        txtEmail = new CustomTextField("Email");
        txtEmail.setBounds(35, 140, 350, 40);
        ((CustomTextField) txtEmail).setHintVerticalOffset(10);
        roundedPanel.add(txtEmail);
        txtEmail.setLayout(null);
        
        txtContrasena = new CustomPasswordField("Contraseña");
        txtContrasena.setBounds(35, 210, 350, 40);
        ((CustomPasswordField) txtContrasena).setHintVerticalOffset(10);
        roundedPanel.add(txtContrasena);
        txtContrasena.setLayout(null);
        
        roundedPanel.add(btnVerContrasena);
        btnVerContrasena.setLayout(null);
        
        txtOlvidasteTuContrasena.setBounds(122, 360, 350, 40);
        roundedPanel.add(txtOlvidasteTuContrasena);
        
        jPanel1.remove(jpFondoAzul);
        jPanel1.add(roundedPanel);
        jpFondoAzul = roundedPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpFondoAzul = new javax.swing.JPanel();
        BienvenidoLabel = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();
        txtOlvidasteTuContrasena = new javax.swing.JLabel();
        btnVerContrasena = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(951, 631));

        jPanel1.setBackground(new java.awt.Color(50, 55, 69));
        jPanel1.setPreferredSize(new java.awt.Dimension(951, 631));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fotoprueba.PNG"))); // NOI18N

        jpFondoAzul.setBackground(new java.awt.Color(31, 38, 76));

        BienvenidoLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BienvenidoLabel.setForeground(new java.awt.Color(255, 255, 255));
        BienvenidoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BienvenidoLabel.setText("Bienvenido a ISSS Salud");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        btnIniciarSesion.setBackground(new java.awt.Color(41, 72, 152));
        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar Sesión");

        txtOlvidasteTuContrasena.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtOlvidasteTuContrasena.setForeground(new java.awt.Color(138, 210, 255));
        txtOlvidasteTuContrasena.setText("¿Olvidaste tu contraseña?");
        txtOlvidasteTuContrasena.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnVerContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/no_ver_password.png"))); // NOI18N
        btnVerContrasena.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerContrasena.setPreferredSize(new java.awt.Dimension(96, 96));

        javax.swing.GroupLayout jpFondoAzulLayout = new javax.swing.GroupLayout(jpFondoAzul);
        jpFondoAzul.setLayout(jpFondoAzulLayout);
        jpFondoAzulLayout.setHorizontalGroup(
            jpFondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoAzulLayout.createSequentialGroup()
                .addGroup(jpFondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoAzulLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(BienvenidoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFondoAzulLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(txtOlvidasteTuContrasena))
                    .addGroup(jpFondoAzulLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoAzulLayout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addGroup(jpFondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoAzulLayout.createSequentialGroup()
                        .addGroup(jpFondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoAzulLayout.createSequentialGroup()
                        .addComponent(btnVerContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        jpFondoAzulLayout.setVerticalGroup(
            jpFondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoAzulLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(BienvenidoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btnVerContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtOlvidasteTuContrasena)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jpFondoAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jpFondoAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrPantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrPantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrPantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrPantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel BienvenidoLabel;
    public javax.swing.JButton btnIniciarSesion;
    public javax.swing.JLabel btnVerContrasena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jpFondoAzul;
    public javax.swing.JPasswordField txtContrasena;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JLabel txtOlvidasteTuContrasena;
    // End of variables declaration//GEN-END:variables
   public class RoundedPanel extends JPanel{
     private int cornerRadius = 20;
     
     public RoundedPanel(){
       super();
       setOpaque(false);
       setLayout(null);
     }
     
     @Override
     protected void paintComponent(Graphics g){
       super.paintComponent(g);
       Graphics2D g2 = (Graphics2D) g;
       g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
       g2.setColor(getBackground());
       g2.fill(new RoundRectangle2D.Float(0, 0, getWidth(), getHeight(), cornerRadius, cornerRadius));
     }
   }
   
   public class CustomTextField extends JTextField{
       
       private String hint;
       private boolean showingHint;
       private int hintVerticalOffset;
       
     public CustomTextField(String hint){
       super();
       this.hint = hint;
       this.showingHint = true;
       this.hintVerticalOffset = 0;
       setOpaque(false);
       setForeground(Color.WHITE);
       setFont(new Font("Arial", Font.ITALIC, 16));
       setCaretColor(Color.WHITE);
       getDocument().addDocumentListener(new DocumentListener(){
         @Override
         public void insertUpdate(DocumentEvent e){
            updateHint();
         }
         
         @Override
         public void removeUpdate(DocumentEvent e) {
                updateHint();
            }   

        @Override
         public void changedUpdate(DocumentEvent e) {
                
            }       
       });
     }
     
     @Override
     protected void paintComponent(Graphics g){
       super.paintComponent(g);
       Graphics2D g2 = (Graphics2D) g.create();
       
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(Color.LIGHT_GRAY);
        g2.fillRect(0, getHeight() - 2, getWidth(), 2);
        
     
        if(showingHint) {
        FontMetrics metrics = g2.getFontMetrics(getFont());
            int x = getInsets().left;
            int y = getInsets().top + metrics.getAscent() + hintVerticalOffset; 
            g2.drawString(hint, x, y);
        }
     }
     
     private void updateHint(){
       showingHint = getDocument().getLength() == 0;
       repaint();
     }
     
     public void setHintVerticalOffset(int offset){
       this.hintVerticalOffset = offset;
       repaint();
     }
     
     @Override
     protected void paintBorder(Graphics g){
     
     }
   }
   
   private static class RoundedButtonUI extends BasicButtonUI {
       @Override 
       public void installUI(JComponent c){
         super.installUI(c);
         ((AbstractButton) c).setOpaque(false);
         ((AbstractButton) c).setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
       }
       
       @Override
       public void paint(Graphics g, JComponent c){
          AbstractButton b = (AbstractButton) c;
          Graphics2D g2 = (Graphics2D) g;
          g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
          
          g2.setColor(b.getBackground());
          g2.fill(new RoundRectangle2D.Float(0, 0, b.getWidth(), b.getHeight(), 50, 50));
          
          g2.setColor(b.getForeground());
          FontMetrics fm = g.getFontMetrics();
          g2.drawString(b.getText(), (b.getWidth() - fm.stringWidth(b.getText())) / 2,
                    (b.getHeight() + fm.getAscent()) / 2 - 2);
          
          g2.dispose();
       }
    }
   
   private class CustomPasswordField extends JPasswordField{
      private String hint;
    private boolean showingHint;
    private int hintVerticalOffset;
    
    public CustomPasswordField(String hint) {
        super();
        this.hint = hint;
        this.showingHint = true;
        this.hintVerticalOffset = 0;
        setOpaque(false);
        setForeground(Color.WHITE);
        setFont(new Font("Arial", Font.ITALIC, 16));
        setCaretColor(Color.WHITE);
        getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateHint();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateHint();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                // No implementation needed
            }
        });
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(Color.LIGHT_GRAY);
        g2.fillRect(0, getHeight() - 2, getWidth(), 2);

        if (showingHint) {
            FontMetrics metrics = g2.getFontMetrics(getFont());
            int x = getInsets().left;
            int y = getInsets().top + metrics.getAscent() + hintVerticalOffset;
            g2.drawString(hint, x, y);
        }
    }
    
    private void updateHint() {
        showingHint = getDocument().getLength() == 0;
        repaint();
    }

    public void setHintVerticalOffset(int offset) {
        this.hintVerticalOffset = offset;
        repaint();
    }

    @Override
    protected void paintBorder(Graphics g) {
        // No border painting
    }
}
   }