/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JPanel;

/**
 *
 * @author Eduardo Padilla
 */
public class jfrPantallaMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form jfrPantallaMenuAdmin
     */
    public jfrPantallaMenuAdmin() {
        initComponents();
        
        jpPanelIzquierdo = new jpPanelIzquierdo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAdmin = new javax.swing.JPanel();
        jpPanelIzquierdo = new javax.swing.JPanel();
        imgMenuHamburguesa = new javax.swing.JLabel();
        jpFondoBotonNavegable = new javax.swing.JPanel();
        btnAdministrador = new javax.swing.JLabel();
        jpPanelSuperior = new javax.swing.JPanel();
        imgLogoNoDesplegado = new javax.swing.JLabel();
        trabajadores = new javax.swing.JLabel();
        fondoCards = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(50, 55, 69));
        setMinimumSize(new java.awt.Dimension(951, 631));

        PanelAdmin.setBackground(new java.awt.Color(50, 55, 69));
        PanelAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpPanelIzquierdo.setBackground(new java.awt.Color(62, 68, 83));
        jpPanelIzquierdo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(204, 204, 204)));
        jpPanelIzquierdo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgMenuHamburguesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu hamburgesa modo oscuro.png"))); // NOI18N
        jpPanelIzquierdo.add(imgMenuHamburguesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jpFondoBotonNavegable.setBackground(new java.awt.Color(41, 72, 152));
        jpFondoBotonNavegable.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(204, 204, 204)));
        jpFondoBotonNavegable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/administrador modo oscuro.png"))); // NOI18N
        jpFondoBotonNavegable.add(btnAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jpPanelIzquierdo.add(jpFondoBotonNavegable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 80, 70));

        PanelAdmin.add(jpPanelIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 630));

        jpPanelSuperior.setBackground(new java.awt.Color(62, 68, 83));
        jpPanelSuperior.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jpPanelSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLogoNoDesplegado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo isss modo oscuro sin desplegar.png"))); // NOI18N
        jpPanelSuperior.add(imgLogoNoDesplegado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        trabajadores.setFont(new java.awt.Font("Roboto", 3, 36)); // NOI18N
        trabajadores.setForeground(new java.awt.Color(255, 255, 255));
        trabajadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trabajadores.setText("Trabajadores");
        jpPanelSuperior.add(trabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        PanelAdmin.add(jpPanelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 870, 115));

        fondoCards.setBackground(new java.awt.Color(70, 76, 92));
        fondoCards.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout fondoCardsLayout = new javax.swing.GroupLayout(fondoCards);
        fondoCards.setLayout(fondoCardsLayout);
        fondoCardsLayout.setHorizontalGroup(
            fondoCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );
        fondoCardsLayout.setVerticalGroup(
            fondoCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        PanelAdmin.add(fondoCards, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 360, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrPantallaMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrPantallaMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrPantallaMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrPantallaMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PanelAdmin;
    public javax.swing.JLabel btnAdministrador;
    public javax.swing.JPanel fondoCards;
    public javax.swing.JLabel imgLogoNoDesplegado;
    public javax.swing.JLabel imgMenuHamburguesa;
    public javax.swing.JPanel jpFondoBotonNavegable;
    public javax.swing.JPanel jpPanelIzquierdo;
    public javax.swing.JPanel jpPanelSuperior;
    public javax.swing.JLabel trabajadores;
    // End of variables declaration//GEN-END:variables
    public class jpPanelIzquierdo extends JPanel{
      @Override
      protected void paintComponent(Graphics g){
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        
        g2d.setColor(Color.WHITE);
        
        int width = getWidth();
        int height = getHeight();
        int thickness = 5;
        
        g2d.fillRect(width - thickness, 0, thickness, height);
      }
    }

}