/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author ricar
 */
public class jfrPantallaMenuAdminJefesEnfermeria extends javax.swing.JFrame {

    /**
     * Creates new form jfrPantallaMenuAdminJefesEnfermeria
     */
    public jfrPantallaMenuAdminJefesEnfermeria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnAgregarTrabajadores = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnNoticiasJ = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnJefes = new javax.swing.JButton();
        btnDoctores = new javax.swing.JButton();
        jpCardsJefesEnfermeria = new javax.swing.JPanel();
        jpCardsJefes = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDuiJefe = new javax.swing.JTextField();
        txtCorreoJefe = new javax.swing.JTextField();
        btnCargarImagenJefe = new javax.swing.JButton();
        btnAgregarJefe = new javax.swing.JButton();
        btnActualizarJefe = new javax.swing.JButton();
        cbSexoJefe = new javax.swing.JComboBox<>();
        profileImageJefe = new javax.swing.JLabel();
        btnLimpiarJefe = new javax.swing.JButton();
        btnEliminarJefe = new javax.swing.JButton();
        cbTipoSangre = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTelefonoJefe = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jdcEdadJefe = new com.toedter.calendar.JDateChooser();
        txtContrasenaJefe = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 760));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(62, 68, 83));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(156, 156, 156)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarTrabajadores.setBackground(new java.awt.Color(41, 72, 152));
        btnAgregarTrabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarJefesEnfermeria.png"))); // NOI18N
        btnAgregarTrabajadores.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(156, 156, 156)));
        btnAgregarTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTrabajadoresActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarTrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 80, 70));

        jButton1.setBackground(new java.awt.Color(62, 68, 83));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu hamburgesa modo oscuro.png"))); // NOI18N
        jButton1.setBorder(null);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        btnNoticiasJ.setBackground(new java.awt.Color(62, 68, 83));
        btnNoticiasJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnNoticiasModoOscuro.png"))); // NOI18N
        btnNoticiasJ.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(156, 156, 156)));
        jPanel2.add(btnNoticiasJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 80, 70));

        btnCerrarSesion.setBackground(new java.awt.Color(62, 68, 83));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida 1.png"))); // NOI18N
        btnCerrarSesion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(156, 156, 156)));
        jPanel2.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 80, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 760));

        jPanel1.setBackground(new java.awt.Color(50, 55, 69));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(62, 68, 83));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(156, 156, 156)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo isss modo oscuro sin desplegar.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Roboto", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Trabajadores");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 230, -1));

        btnJefes.setBackground(new java.awt.Color(41, 72, 152));
        btnJefes.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        btnJefes.setForeground(new java.awt.Color(255, 255, 255));
        btnJefes.setText("Jefes de enfermería");
        jPanel3.add(btnJefes, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, 170, 40));

        btnDoctores.setBackground(new java.awt.Color(183, 184, 187));
        btnDoctores.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        btnDoctores.setForeground(new java.awt.Color(61, 61, 61));
        btnDoctores.setText("Doctores");
        jPanel3.add(btnDoctores, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, 110, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 110));

        jpCardsJefesEnfermeria.setBackground(new java.awt.Color(70, 76, 92));
        jpCardsJefesEnfermeria.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(156, 156, 156)));
        jpCardsJefesEnfermeria.setLayout(new java.awt.BorderLayout());

        jpCardsJefes.setBackground(new java.awt.Color(70, 76, 92));
        jpCardsJefes.setLayout(new java.awt.BorderLayout());
        jpCardsJefesEnfermeria.add(jpCardsJefes, java.awt.BorderLayout.CENTER);

        jPanel1.add(jpCardsJefesEnfermeria, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 480, 650));

        jLabel5.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Edad");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 50, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Foto del jefe de enfermería");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 230, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Teléfono");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 140, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Correo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 60, -1));

        jLabel12.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tipo de Sangre");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 150, -1));

        txtDuiJefe.setBackground(new java.awt.Color(50, 55, 65));
        txtDuiJefe.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        txtDuiJefe.setForeground(java.awt.Color.white);
        txtDuiJefe.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(132, 135, 143)));
        txtDuiJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuiJefeActionPerformed(evt);
            }
        });
        jPanel1.add(txtDuiJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 235, 290, 30));

        txtCorreoJefe.setBackground(new java.awt.Color(50, 55, 65));
        txtCorreoJefe.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        txtCorreoJefe.setForeground(java.awt.Color.white);
        txtCorreoJefe.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(132, 135, 143)));
        txtCorreoJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoJefeActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreoJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 315, 290, 30));

        btnCargarImagenJefe.setBackground(new java.awt.Color(41, 72, 152));
        btnCargarImagenJefe.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        btnCargarImagenJefe.setForeground(java.awt.Color.white);
        btnCargarImagenJefe.setText("Cargar Imagen");
        btnCargarImagenJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarImagenJefeActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargarImagenJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 140, 50));

        btnAgregarJefe.setBackground(new java.awt.Color(41, 72, 152));
        btnAgregarJefe.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        btnAgregarJefe.setForeground(java.awt.Color.white);
        btnAgregarJefe.setText("Agregar");
        btnAgregarJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarJefeActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 120, 50));

        btnActualizarJefe.setBackground(new java.awt.Color(41, 72, 152));
        btnActualizarJefe.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        btnActualizarJefe.setForeground(java.awt.Color.white);
        btnActualizarJefe.setText("Actualizar");
        jPanel1.add(btnActualizarJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, 120, 50));

        cbSexoJefe.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        cbSexoJefe.setForeground(java.awt.Color.black);
        cbSexoJefe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        cbSexoJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoJefeActionPerformed(evt);
            }
        });
        jPanel1.add(cbSexoJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 290, 30));

        profileImageJefe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/profile.jpg"))); // NOI18N
        jPanel1.add(profileImageJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 200, 200));

        btnLimpiarJefe.setBackground(new java.awt.Color(41, 72, 152));
        btnLimpiarJefe.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        btnLimpiarJefe.setForeground(java.awt.Color.white);
        btnLimpiarJefe.setText("Limpiar");
        btnLimpiarJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarJefeActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiarJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 660, 120, 50));

        btnEliminarJefe.setBackground(new java.awt.Color(41, 72, 152));
        btnEliminarJefe.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        btnEliminarJefe.setForeground(java.awt.Color.white);
        btnEliminarJefe.setText("Eliminar");
        btnEliminarJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarJefeActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 660, 120, 50));

        cbTipoSangre.setForeground(java.awt.Color.black);
        cbTipoSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        jPanel1.add(cbTipoSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 290, 30));

        jLabel13.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Sexo");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 50, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DUI");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 260, -1));

        txtTelefonoJefe.setBackground(new java.awt.Color(50, 55, 65));
        txtTelefonoJefe.setForeground(java.awt.Color.white);
        txtTelefonoJefe.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(132, 135, 143)));
        jPanel1.add(txtTelefonoJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 155, 290, 30));

        jLabel10.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contraseña");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 100, -1));

        jdcEdadJefe.setBackground(new java.awt.Color(50, 55, 65));
        jdcEdadJefe.setForeground(java.awt.Color.black);
        jdcEdadJefe.setDateFormatString("dd-MM-yyyy");
        jPanel1.add(jdcEdadJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, 260, 30));

        txtContrasenaJefe.setBackground(new java.awt.Color(50, 55, 65));
        txtContrasenaJefe.setForeground(java.awt.Color.white);
        txtContrasenaJefe.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(132, 135, 143)));
        jPanel1.add(txtContrasenaJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 395, 290, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 1120, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTrabajadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarTrabajadoresActionPerformed

    private void txtDuiJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuiJefeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuiJefeActionPerformed

    private void txtCorreoJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoJefeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoJefeActionPerformed

    private void btnCargarImagenJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarImagenJefeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarImagenJefeActionPerformed

    private void btnAgregarJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarJefeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarJefeActionPerformed

    private void cbSexoJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoJefeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSexoJefeActionPerformed

    private void btnLimpiarJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarJefeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarJefeActionPerformed

    private void btnEliminarJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarJefeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarJefeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrPantallaMenuAdminJefesEnfermeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrPantallaMenuAdminJefesEnfermeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrPantallaMenuAdminJefesEnfermeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrPantallaMenuAdminJefesEnfermeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrPantallaMenuAdminJefesEnfermeria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarJefe;
    public javax.swing.JButton btnAgregarJefe;
    public javax.swing.JButton btnAgregarTrabajadores;
    public javax.swing.JButton btnCargarImagenJefe;
    public javax.swing.JButton btnCerrarSesion;
    public javax.swing.JButton btnDoctores;
    public javax.swing.JButton btnEliminarJefe;
    public javax.swing.JButton btnJefes;
    public javax.swing.JButton btnLimpiarJefe;
    public javax.swing.JButton btnNoticiasJ;
    public javax.swing.JComboBox<String> cbSexoJefe;
    public javax.swing.JComboBox<String> cbTipoSangre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public com.toedter.calendar.JDateChooser jdcEdadJefe;
    public javax.swing.JPanel jpCardsJefes;
    public javax.swing.JPanel jpCardsJefesEnfermeria;
    public javax.swing.JLabel profileImageJefe;
    public javax.swing.JPasswordField txtContrasenaJefe;
    public javax.swing.JTextField txtCorreoJefe;
    public javax.swing.JTextField txtDuiJefe;
    public javax.swing.JTextField txtTelefonoJefe;
    // End of variables declaration//GEN-END:variables
}
