/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author ricar
 */
public class PanelPersonalAdmin extends javax.swing.JPanel {

    /**
     * Creates new form PanelPersonalAdmin
     */
    public PanelPersonalAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSolicitudes = new javax.swing.JButton();
        btnAgendadas = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1120, 110));
        setPreferredSize(new java.awt.Dimension(1120, 110));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(62, 68, 83));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(156, 156, 156)));
        jPanel3.setMinimumSize(new java.awt.Dimension(1120, 110));
        jPanel3.setPreferredSize(new java.awt.Dimension(1120, 110));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo isss modo oscuro sin desplegar.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Roboto", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Trabajadores");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));

        btnSolicitudes.setBackground(new java.awt.Color(41, 72, 152));
        btnSolicitudes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnSolicitudes.setText("Doctores");
        jPanel3.add(btnSolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 110, 40));

        btnAgendadas.setBackground(new java.awt.Color(183, 184, 187));
        btnAgendadas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAgendadas.setForeground(new java.awt.Color(61, 61, 61));
        btnAgendadas.setText("Jefes de enfermería");
        jPanel3.add(btnAgendadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 170, 40));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 110));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgendadas;
    public javax.swing.JButton btnSolicitudes;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
