/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Eduardo Padilla
 */
public class PanelBienvenidaChat extends javax.swing.JPanel {

    /**
     * Creates new form PanelBienvenidaChat
     */
    public PanelBienvenidaChat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlFotoLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(50, 55, 69));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlFotoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fotoprueba.PNG"))); // NOI18N
        add(jlFotoLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 144, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("!Contacta con tus pacientes!");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 250, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jlFotoLogo;
    // End of variables declaration//GEN-END:variables
}
