/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ctrlPantallaMenuDoctor;

/**
 *
 * @author ricar
 */
public class PanelMenuMensajeriaSinDesplegar extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuMensajeriaSinDesplegar
     */
    public PanelMenuMensajeriaSinDesplegar() {
        initComponents();
        
        PanelMenuMensajeriaSinDesplegar panel= this;
        jfrPantallaMenuDoctor vista = new jfrPantallaMenuDoctor();
        
        ctrlPantallaMenuDoctor controlador = new ctrlPantallaMenuDoctor(vista, panel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenuDesplegable = new javax.swing.JButton();
        btnCitasMedicas = new javax.swing.JButton();
        no = new javax.swing.JButton();

        setBackground(new java.awt.Color(62, 68, 83));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(156, 156, 156)));
        setMinimumSize(new java.awt.Dimension(80, 750));
        setPreferredSize(new java.awt.Dimension(80, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenuDesplegable.setBackground(new java.awt.Color(62, 68, 83));
        btnMenuDesplegable.setForeground(new java.awt.Color(62, 68, 83));
        btnMenuDesplegable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu hamburgesa modo oscuro.png"))); // NOI18N
        btnMenuDesplegable.setBorder(null);
        add(btnMenuDesplegable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        btnCitasMedicas.setBackground(new java.awt.Color(62, 68, 83));
        btnCitasMedicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/citas medicas modo oscuro.png"))); // NOI18N
        btnCitasMedicas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(156, 156, 156)));
        add(btnCitasMedicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 80, 70));

        no.setBackground(new java.awt.Color(41, 72, 152));
        no.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono chat modo oscuro.png"))); // NOI18N
        no.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(156, 156, 156)));
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 80, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCitasMedicas;
    public javax.swing.JButton btnMenuDesplegable;
    private javax.swing.JButton no;
    // End of variables declaration//GEN-END:variables
}
