/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ctrlPantallaMenuDoctor;
import Modelo.CitasMedicas;
import Modelo.ExpedientesMedicos;
import Modelo.Usuarios;

/**
 *
 * @author ricar
 */
public class PanelInfoCitaDoctor extends javax.swing.JPanel {

    /**
     * Creates new form PanelInfoCitaDoctor
     */
    public PanelInfoCitaDoctor() {
        initComponents();
    }
    
    public static void initPanelInfoCitaDoctor(){
            
        jfrPantallaMenuDoctor vista = new jfrPantallaMenuDoctor();
        PanelChatDoctoresSinDesplegar panel = new PanelChatDoctoresSinDesplegar();
        PanelCitasMedicasDoctor panel1 = new PanelCitasMedicasDoctor();
        PanelInfoCitaDoctor panel2 = new PanelInfoCitaDoctor();
        PanelExpedienteMedico panel3 = new PanelExpedienteMedico();
        CitasMedicas modelo = new CitasMedicas();
        ExpedientesMedicos modelo2 = new ExpedientesMedicos();
        Usuarios modelo3 = new Usuarios();
        
        ctrlPantallaMenuDoctor controlador = new ctrlPantallaMenuDoctor(vista, panel, panel1, panel2, panel3, modelo, modelo2, modelo3);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDuiPaciente = new javax.swing.JTextField();
        txtNombreDoctor = new javax.swing.JTextField();
        txtSexoPaciente = new javax.swing.JTextField();
        txtHoraCita = new javax.swing.JTextField();
        txtCorreoPaciente = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        txtTipoSangrePaciente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtFechaCita = new javax.swing.JTextField();
        btnExpediente = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(740, 560));
        setPreferredSize(new java.awt.Dimension(740, 560));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(70, 76, 92));
        jPanel7.setMinimumSize(new java.awt.Dimension(740, 560));
        jPanel7.setName(""); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(740, 560));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DUI del paciente");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 230, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 3, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Doctor designado");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 170, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 3, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo sangre del paciente");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 230, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 3, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sexo del paciente");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 190, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 3, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Correo del paciente");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 190, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 3, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Hora de la cita");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 160, -1));

        txtDuiPaciente.setBackground(new java.awt.Color(70, 76, 92));
        txtDuiPaciente.setFont(new java.awt.Font("Raleway Thin", 2, 13)); // NOI18N
        txtDuiPaciente.setForeground(new java.awt.Color(255, 255, 255));
        txtDuiPaciente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(144, 148, 157)));
        jPanel7.add(txtDuiPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 230, 30));

        txtNombreDoctor.setBackground(new java.awt.Color(70, 76, 92));
        txtNombreDoctor.setFont(new java.awt.Font("Raleway Thin", 2, 13)); // NOI18N
        txtNombreDoctor.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreDoctor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(144, 148, 157)));
        jPanel7.add(txtNombreDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 270, 30));

        txtSexoPaciente.setBackground(new java.awt.Color(70, 76, 92));
        txtSexoPaciente.setFont(new java.awt.Font("Raleway Thin", 2, 13)); // NOI18N
        txtSexoPaciente.setForeground(new java.awt.Color(255, 255, 255));
        txtSexoPaciente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(144, 148, 157)));
        jPanel7.add(txtSexoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 270, 30));

        txtHoraCita.setBackground(new java.awt.Color(70, 76, 92));
        txtHoraCita.setFont(new java.awt.Font("Raleway Thin", 2, 13)); // NOI18N
        txtHoraCita.setForeground(new java.awt.Color(255, 255, 255));
        txtHoraCita.setToolTipText("");
        txtHoraCita.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(144, 148, 157)));
        jPanel7.add(txtHoraCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 350, 30));

        txtCorreoPaciente.setBackground(new java.awt.Color(70, 76, 92));
        txtCorreoPaciente.setFont(new java.awt.Font("Raleway Thin", 2, 13)); // NOI18N
        txtCorreoPaciente.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreoPaciente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(144, 148, 157)));
        jPanel7.add(txtCorreoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 270, 30));

        btnLimpiar.setBackground(new java.awt.Color(41, 72, 152));
        btnLimpiar.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(null);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel7.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 120, 40));

        txtTipoSangrePaciente.setBackground(new java.awt.Color(70, 76, 92));
        txtTipoSangrePaciente.setFont(new java.awt.Font("Raleway Thin", 2, 13)); // NOI18N
        txtTipoSangrePaciente.setForeground(new java.awt.Color(255, 255, 255));
        txtTipoSangrePaciente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(144, 148, 157)));
        jPanel7.add(txtTipoSangrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 230, 30));

        jLabel11.setFont(new java.awt.Font("Roboto", 3, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Fecha de la cita");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 160, -1));

        txtFechaCita.setBackground(new java.awt.Color(70, 76, 92));
        txtFechaCita.setFont(new java.awt.Font("Raleway Thin", 2, 13)); // NOI18N
        txtFechaCita.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaCita.setToolTipText("");
        txtFechaCita.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(144, 148, 157)));
        jPanel7.add(txtFechaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 350, 30));

        btnExpediente.setBackground(new java.awt.Color(41, 72, 152));
        btnExpediente.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        btnExpediente.setForeground(new java.awt.Color(255, 255, 255));
        btnExpediente.setText("Ver expediente");
        btnExpediente.setBorder(null);
        jPanel7.add(btnExpediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 120, 40));

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnExpediente;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel7;
    public javax.swing.JTextField txtCorreoPaciente;
    public javax.swing.JTextField txtDuiPaciente;
    public javax.swing.JTextField txtFechaCita;
    public javax.swing.JTextField txtHoraCita;
    public javax.swing.JTextField txtNombreDoctor;
    public javax.swing.JTextField txtSexoPaciente;
    public javax.swing.JTextField txtTipoSangrePaciente;
    // End of variables declaration//GEN-END:variables
}
